
--TABLE CSYT
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT) VALUES (N'Ha Noi', N'10 De La Thanh', '0123456789');
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT) VALUES (N'Da Nang', N'20 Tran Phu', '0147852369');
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT) VALUES (N'Ho Chi Minh', N'227 Nguyen Van Cu', '0123789456');

--TABLE BENHNHAN
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (1,N'Nguyen Van A', '123456', TO_DATE('2001/12/16 ', 'yyyy/mm/dd '), N'21/2b', N'Tran Phu', N'Tp. Da Lat', N'Lâm Ðong', N'Ho', N'Không có', N'Không có');
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (2,N'Le Van B', '1234567', TO_DATE('2001/2/16 ', 'yyyy/mm/dd '), N'21/2b', N'Tran Phu', N'Tp. Sa Pa', N'Lào Cai', N'Ho', N'Không có', N'Không có');
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (3,N'Dam Van C', '1234568', TO_DATE('2001/5/16 ', 'yyyy/mm/dd '), N'21/2b', N'Tran Phu', N'Tp. Ðà Nang', N'Ðà Nang', N'', N'', N'');

--TABLE NHANVIEN
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Park Chaeyoung',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'123',N'Tp. Ðà L?t','0852576282',1,1,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Park Rose',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'1234',N'Tp. Ðà L?t','0852576212',1,2,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Park Roseanne',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'1235',N'Tp. Ðà L?t','0852345282',1,3,N'Da khoa');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Rose',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'1236',N'Tp. Ðà L?t','0852545282',1,4,N'Da khoa');

INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Kim Jisoo',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'1233',N'Tp. Ðà L?t','0852576225',2,1,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Jisoo',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12334',N'Tp. Ðà L?t','0852576225',2,2,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Kim Chi Chu',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12335',N'Tp. Ðà L?t','0852345225',2,3,N'Rang ham mat');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'BP Jisoo',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12336',N'Tp. Ðà L?t','0852545225',2,4,N'Ða khoa');

INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'La Lisa',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'1243',N'Tp. Ðà L?t','0855676225',3,1,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'Lisa',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12344',N'Tp. Ðà L?t','0852654225',3,2,N'');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'La Li Sa',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12345',N'Tp. Ðà L?t','0854567225',3,3,N'Long nguc');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA) VALUES(N'BP Lisa',N'N?', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12346',N'Tp. Ðà L?t','0852544325',3,4,N'Ða khoa');

--TABLE KHOA
INSERT INTO KHOA(TENKHOA) VALUES(N'Da khoa');
INSERT INTO KHOA(TENKHOA) VALUES(N'Rang ham mat');
INSERT INTO KHOA(TENKHOA) VALUES(N'Long nguc');

--TABLE HSBA
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(1, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), N'Viêm màng túi',3,1,1,N'Viêm');
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(2, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), N'Viêm màng túi',7,1,2,N'Viêm');
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(3, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), N'Viêm màng túi',11,1,3,N'Viêm');

--TABLE HSBA_DV
INSERT INTO HSBA_DV(MADV, NGAY, MAKTV, KETQUA) VALUES(1, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), 2, N'OK');
INSERT INTO HSBA_DV(MADV, NGAY, MAKTV, KETQUA) VALUES(2, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), 6, N'FAIL');
INSERT INTO HSBA_DV(MADV, NGAY, MAKTV, KETQUA) VALUES(3, TO_DATE('2022/6/23 ', 'yyyy/mm/dd'), 10, N'OK');