-----------------------TC2------------------------
-- có 5 nhân viên thuộc sở y tế với vai trò "thanh tra"
-- các nhân viên giữ vai trò thanh tra có thể đ�?c dữ liệu trên tất cả các bảng
-- nhưng không có quy�?n thêm xoá sửa các bảng này

-- B1: drop user
DROP USER THANHTRA_1 CASCADE ;
DROP USER THANHTRA_2 CASCADE ;
DROP USER THANHTRA_3 CASCADE ;
DROP USER THANHTRA_4 CASCADE ;
DROP USER THANHTRA_5 CASCADE ;

-- B2: tạo 5 user thanh tra
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER THANHTRA_1 IDENTIFIED BY 1;
CREATE USER THANHTRA_2 IDENTIFIED BY 2;
CREATE USER THANHTRA_3 IDENTIFIED BY 3;
CREATE USER THANHTRA_4 IDENTIFIED BY 4;
CREATE USER THANHTRA_5 IDENTIFIED BY 5;

GRANT CREATE SESSION TO THANHTRA_1;
GRANT CREATE SESSION TO THANHTRA_2;
GRANT CREATE SESSION TO THANHTRA_3;
GRANT CREATE SESSION TO THANHTRA_4;
GRANT CREATE SESSION TO THANHTRA_5;

-- B3: xoa role
DROP ROLE ROLE_THANHTRA;

-- B4: tao role
CREATE ROLE ROLE_THANHTRA;

-- B5: gan role cho user
GRANT ROLE_THANHTRA TO THANHTRA_1;
GRANT ROLE_THANHTRA TO THANHTRA_2;
GRANT ROLE_THANHTRA TO THANHTRA_3;
GRANT ROLE_THANHTRA TO THANHTRA_4;
GRANT ROLE_THANHTRA TO THANHTRA_5;

-- B6: gan quyen cho role
GRANT SELECT ON HSBA_DV TO ROLE_THANHTRA;
GRANT SELECT ON NHANVIEN TO ROLE_THANHTRA;
GRANT SELECT ON BENHNHAN TO ROLE_THANHTRA;
GRANT SELECT ON KHOA TO ROLE_THANHTRA;
GRANT SELECT ON CSYT TO ROLE_THANHTRA;
GRANT SELECT ON HSBA TO ROLE_THANHTRA;


----------------------------
--TC5
--Tao view
CREATE OR REPLACE VIEW Select_HSBA AS
SELECT HS.*, DVV.MADV, DVV.NGAY AS DV_NGAY, DVV.MAKTV, DVV.KETQUA
FROM HSBA HS, NHANVIEN NV, KHOA K, HSBA_DV DVV
WHERE HS.MACSYT = NV.CSYT
AND NV.USERNAME = SYS_CONTEXT ('USERENV', 'SESSION_USER')
AND HS.MAKHOA = K.MA_KHOA 
AND K.TENKHOA = NV.CHUYENKHOA
AND DVV.MA_HSBA = HS.MAHSBA
AND NV.VAITRO = 4;

--TAOUSER&ROLE
-- B1: drop user

--TAOUSER&ROLE
-- B1: drop user
DROP USER NV_1 CASCADE ;
DROP USER NV_2 CASCADE ;
DROP USER NV_3 CASCADE ;
DROP USER NV_4 CASCADE ;
DROP USER NV_5 CASCADE ;

-- B2: TAO 5 user NV
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER NV_1 IDENTIFIED BY 1;
CREATE USER NV_2 IDENTIFIED BY 2;
CREATE USER NV_3 IDENTIFIED BY 3;
CREATE USER NV_4 IDENTIFIED BY 4;
CREATE USER NV_5 IDENTIFIED BY 5;

GRANT CREATE SESSION TO NV_1;
GRANT CREATE SESSION TO NV_2;
GRANT CREATE SESSION TO NV_3;
GRANT CREATE SESSION TO NV_4;
GRANT CREATE SESSION TO NV_5;

-- B3: xoa role
DROP ROLE ROLE_NHANVIEN;

-- B4: tao role
CREATE ROLE ROLE_NHANVIEN;

-- B5: gan role cho user
GRANT ROLE_NHANVIEN TO NV_1;
GRANT ROLE_NHANVIEN TO NV_2;
GRANT ROLE_NHANVIEN TO NV_3;
GRANT ROLE_NHANVIEN TO NV_4;
GRANT ROLE_NHANVIEN TO NV_5;
--GAN QUYEN CHO ROLE
GRANT SELECT ON Select_HSBA TO ROLE_NHANVIEN;